### ISSUE TITLE
Choose.C(x, 0) = 1, not 0

### ISSUE THREAD

**Issue by rhapsodyv** [postmodern/combinatorics#3]
Hi,

I think this line is wrong:

https://github.com/postmodern/combinatorics/blob/master/lib/combinatorics/choose/cardinality.rb#L41

Any reason for it?

```
C(x, 0) = 
        x!         
 ----------------- 
 0!  *  (x  -  0)! 

        x!         
----------------- 
    1  *  x! 
= 1
```

**Comment by postmodern** [comment]
I'm not entirely sure. The docs reference [Binomial coefficient](https://en.wikipedia.org/wiki/Binomial_coefficient) but the method is named `cardinality`.

**Comment by rhapsodyv** [comment]
Well, the C method call cardinality. If cardinality is correct, C isn't... Right?

https://github.com/postmodern/combinatorics/blob/master/lib/combinatorics/choose/cardinality.rb#L60

**Comment by rhapsodyv** [comment]
http://www.wolframalpha.com/input/?i=C%28x%2C0%29

**Comment by postmodern** [comment]
Combing back to this project. I think `C(x,0) = 1` is because a combination of 0 elements from a list of N elements is always the empty-list/empty-set.

```ruby
[1,2,3].combination(0).to_a
# => [[]]
```
